### ISSUE TITLE
Possible glitch in class method with f-string

### ISSUE THREAD

**Issue by xiaket** [numirias/semshi#38] opened 2019-05-02 02:22 UTC
Could be a duplicate of #31 . However, in my case, I don't have any format specifiers.

```
#!/usr/bin/env python3
import logging


class SomeClass:
    def demo(self, name):
        security_group = []
        logging.warning(
            f"Security group {security_group} not working"
            f"foo bar {name}."
        )

c = SomeClass()
c.demo("world")
```

**Comment by xiaket** [comment] 2019-05-02 02:24
In my neovim, the color of `"Sec` is blue, just as `name`. Hope you can reproduce this on your end.

Thanks for this great plugin btw, I cannot live without it now.   :D

**Comment by numirias** [comment] 2019-05-02 02:36
Thanks for reporting! I can reproduce the issue and will look into it.

> Thanks for this great plugin btw, I cannot live without it now. :D 

Great to hear someone's using it in their daily workflow.

**Comment by lervag** [comment] 2019-10-04 08:07
I also have the same issue. Seems to me to be the only thing I miss from `python-syntax` right now.

**Comment by numirias** [comment] 2019-10-04 08:40
Unfortunately this appears to be another bug in Python's `ast` module, similar to #31. In this case, in a multi-line f-string, the syntax tree reports incorrect positions on lines beyond the first one.

Code example:

```python
(
    f'aaa{foo}bbb'
    f'ccc{bar}ddd'
    f'eee{baz}fff'
)
```
Relevant part of the syntax tree:

```python
JoinedStr(
    lineno=2,
    col_offset=4,
    values=[
        Str(lineno=2, col_offset=4, s='aaa'),
        FormattedValue(
            lineno=2,
            col_offset=4,
            value=Name(lineno=2, col_offset=10, id='foo', ctx=Load()),
            conversion=-1,
            format_spec=None,
        ),
        Str(lineno=2, col_offset=4, s='bbbccc'),
        FormattedValue(
            lineno=2,
            col_offset=4,
            value=Name(lineno=2, col_offset=5, id='bar', ctx=Load()),
            conversion=-1,
            format_spec=None,
        ),
        Str(lineno=2, col_offset=4, s='dddcccaaaaaaaaaaaaaa'),
        FormattedValue(
            lineno=2,
            col_offset=4,
            value=Name(lineno=2, col_offset=5, id='baz', ctx=Load()),
            conversion=-1,
            format_spec=None,
        ),
        Str(lineno=2, col_offset=4, s='ddd'),
    ],
),
```
The reported position for `foo` is correct (2,10), but not for `bar` (2,5) and `baz` (2,5).

I'm not sure there is an elegant workaround for this, but I'm open for suggestions. Also, I might introduce a switch to disable highlighting in f-strings.

I'll probably add this example to the Python [bug report](https://bugs.python.org/issue35212). Let's hope they will patch it at some point.

**Comment by numirias** [comment] 2019-10-04 08:54
Duplicate of #31

**Closed by numirias** 2019-10-04 08:54 UTC
Labels: bug

**Comment by ObserverOfTime** [comment] 2019-12-03 12:40
The switch would be nice because I'm also having issues with f-strings.
